version: '3.7'

services:
  mysql:
    container_name: school-mysql
    image: school-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - school-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: school-app
    image: school-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - school-network

networks:
  school-network:
 