openapi: 3.0.3
info:
  title: M2 - G24
  description: Gestão Escolar
  termsOfService: https://github.com/INF22DWIG24/ReportDW1
  contact:
    name: M2 - G24
    email: a039738@umaia.pt
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080
  description: My localhost
  variables:
    basePath:
      default: /
paths:
  /disciplina:
    get:
      tags:
      - Disciplina
      summary: Retrieve all disciplinas
      operationId: retrieveDisciplinas
      responses:
        "200":
          description: Return all disciplinas from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disciplina'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Disciplinas
                items:
                  $ref: '#/components/schemas/Disciplina'
      x-swagger-router-controller: Disciplina
    post:
      tags:
      - Disciplina
      summary: Create disciplina
      operationId: createdisciplina
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Disciplina'
          application/xml:
            schema:
              $ref: '#/components/schemas/Disciplina'
      responses:
        "200":
          description: Create a Disciplina instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disciplina'
      x-swagger-router-controller: Disciplina
  /disciplina/{id}:
    get:
      tags:
      - Disciplina
      summary: Retrieve disciplina
      operationId: retrieveDisciplina
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrive Disciplina id 1
            value: 1
          two:
            summary: Retrive Disciplina id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disciplina'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Disciplina
    put:
      tags:
      - Disciplina
      summary: Update Disciplina
      operationId: updateDisciplina
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Disciplina id 1
            value: 1
          two:
            summary: Update Disciplina id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Disciplina'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Disciplina put sucess
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Disciplina
    delete:
      tags:
      - Disciplina
      summary: Delete Disciplina
      operationId: deleteDisciplina
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Disciplina id 1
            value: 1
          two:
            summary: Delete Disciplina id 2
            value: 2
      responses:
        "204":
          description: No content
        "404":
          description: id not found
      x-swagger-router-controller: Disciplina
  /disciplina/{id}/alunos:
    get:
      tags:
      - Disciplina
      summary: Retrieve alunos by id
      operationId: retrieveDisciplinaAlunos
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrive Disciplina id 1
            value: 1
          two:
            summary: Retrive Disciplina id 2
            value: 2
      responses:
        "200":
          description: Array of alunos instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disciplina'
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: id not found
        x-swagger-router-controller: Disciplina
      x-swagger-router-controller: Disciplina
  /curso:
    get:
      tags:
      - Curso
      summary: Retrieve Curso
      operationId: retrieveCursos
      responses:
        "200":
          description: Array of curso model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Curso'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Lesson
                items:
                  $ref: '#/components/schemas/Curso'
      x-swagger-router-controller: Curso
    post:
      tags:
      - Curso
      summary: Create Curso
      operationId: createCurso
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Curso'
          application/xml:
            schema:
              $ref: '#/components/schemas/Curso'
      responses:
        "200":
          description: Create a Curso instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curso'
      x-swagger-router-controller: Curso
  /curso/{id}:
    get:
      tags:
      - Curso
      summary: Retrieve curso
      operationId: retrieveCurso
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrive Curso id 1
            value: 1
          two:
            summary: Retrive Curso id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curso'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Curso
    put:
      tags:
      - Curso
      summary: Update Curso
      operationId: updateCurso
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Curso id 1
            value: 1
          two:
            summary: Update Curso id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Curso'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: curso PUT success
                x-content-type: application/json
        "400":
          description: Bad Request
        "404":
          description: id not found
      x-swagger-router-controller: Curso
    delete:
      tags:
      - Curso
      summary: Delete Curso
      operationId: deleteCurso
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Curso id 1
            value: 1
          two:
            summary: Delete Curso id 2
            value: 2
      responses:
        "204":
          description: No content
        "404":
          description: id not found
      x-swagger-router-controller: Curso
  /curso/{id}/disciplina:
    post:
      tags:
      - Curso
      summary: Create disciplina by curso
      operationId: createdisciplina_by_curso
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CursoDisciplina'
          application/xml:
            schema:
              $ref: '#/components/schemas/CursoDisciplina'
      responses:
        "200":
          description: Create a Disciplina model instances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursoDisciplina'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Curso
  /professor:
    get:
      tags:
      - Professor
      summary: Retrieve Professores
      operationId: retrieveProfessores
      responses:
        "200":
          description: Array of Professor model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Lesson
                items:
                  $ref: '#/components/schemas/Professor'
      x-swagger-router-controller: Professor
    post:
      tags:
      - Professor
      summary: Create Professor
      operationId: createProfessor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Professor'
          application/xml:
            schema:
              $ref: '#/components/schemas/Professor'
      responses:
        "200":
          description: Create a Professor model instances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Professor'
      x-swagger-router-controller: Professor
  /professor/{id}:
    get:
      tags:
      - Professor
      summary: Retrieve Professor
      operationId: retrieveProfessor
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrive Professor id 1
            value: 1
          two:
            summary: Retrive Professor id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Professor'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Professor
    put:
      tags:
      - Professor
      summary: Update Professor
      operationId: updateProfessor
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Professor id 1
            value: 1
          two:
            summary: Update Professor id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Professor'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Professor PUT success
                x-content-type: application/json
        "400":
          description: Bad Request
        "404":
          description: id not found
      x-swagger-router-controller: Professor
    delete:
      tags:
      - Professor
      summary: Delete Professor
      operationId: deleteProfessor
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Professor id 1
            value: 1
          two:
            summary: Delete Professor id 2
            value: 2
      responses:
        "204":
          description: No content
        "404":
          description: id not found
      x-swagger-router-controller: Professor
  /aluno:
    get:
      tags:
      - Aluno
      summary: Retrieve Alunos
      operationId: retrieveAlunos
      responses:
        "200":
          description: Array of Aluno model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: Aluno
                items:
                  $ref: '#/components/schemas/Aluno'
      x-swagger-router-controller: Aluno
    post:
      tags:
      - Aluno
      summary: Create Aluno
      operationId: createAluno
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
          application/xml:
            schema:
              $ref: '#/components/schemas/Aluno'
      responses:
        "200":
          description: Create a Aluno model instances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
      x-swagger-router-controller: Aluno
  /aluno/{id}:
    get:
      tags:
      - Aluno
      summary: Retrieve Aluno
      operationId: retrieveAluno
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrive Aluno id 1
            value: 1
          two:
            summary: Retrive Aluno id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
        "400":
          description: Bad request
        "404":
          description: id not found
      x-swagger-router-controller: Aluno
    put:
      tags:
      - Aluno
      summary: Update Aluno
      operationId: updateAluno
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Aluno id 1
            value: 1
          two:
            summary: Update Aluno id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Aluno PUT success
                x-content-type: application/json
        "400":
          description: Bad Request
        "404":
          description: id not found
      x-swagger-router-controller: Aluno
    delete:
      tags:
      - Aluno
      summary: Delete Aluno
      operationId: deleteAluno
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Aluno id 1
            value: 1
          two:
            summary: Delete Aluno id 2
            value: 2
      responses:
        "204":
          description: No content
        "404":
          description: id not found
      x-swagger-router-controller: Aluno
components:
  schemas:
    Disciplina:
      title: Disciplina
      required:
      - ano
      - curso_id
      - nome
      - professor_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        ano:
          type: integer
          format: int64
        curso_id:
          type: integer
          format: int64
        nome:
          type: string
        professor_id:
          type: integer
          format: int64
      additionalProperties: false
      example:
        ano: 1
        curso_id: 0
        nome: nome
        professor_id: 0
    CursoDisciplina:
      title: CursoDisciplina
      required:
      - ano
      - nome
      - professor_id
      type: object
      properties:
        id:
          type: integer
          format: int64
        ano:
          type: integer
          format: int64
        curso_id:
          type: integer
          format: int64
        nome:
          type: string
        professor_id:
          type: integer
          format: int64
      additionalProperties: false
      example:
        ano: 1
        nome: nome
        professor_id: 0
    Curso:
      title: Curso
      required:
      - nome
      - nrAnos
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        nrAnos:
          type: integer
          format: int64
      additionalProperties: false
      example:
        nome: nome
        nrAnos: 0
    Professor:
      title: Professor
      required:
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
      additionalProperties: false
      example:
        nome: nome
    Aluno:
      title: Aluno
      required:
      - disciplina_id
      - n_aluno
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        n_aluno:
          type : string
        disciplina_id:
          type: integer
          format: int64
      additionalProperties: false
      example:
        nome: nome
        disciplina_id: 0
